"""update book tags

Revision ID: 7daa5231477a
Revises: 1726e5ee3582
Create Date: 2026-08-12 18:13:23.214898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '7daa5231477a'
down_revision: Union[str, Sequence[str], None] = '1726e5ee3582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktag',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    op.drop_table('book_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tags',
    sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], name=op.f('book_tags_book_uid_fkey')),
    sa.ForeignKeyConstraint(['tag_uid'], ['tags.uid'], name=op.f('book_tags_tag_uid_fkey')),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid', name=op.f('book_tags_pkey'))
    )
    op.drop_table('booktag')
    # ### end Alembic commands ###
