"""add verification email sent at

Revision ID: 91a4c102d536
Revises: 7daa5231477a
Create Date: 2026-08-15 23:58:47.875487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91a4c102d536'
down_revision: Union[str, Sequence[str], None] = '7daa5231477a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('users', sa.Column('verification_email_sent_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_email_sent_at')
    # ### end Alembic commands ###
